server:
  port: 8020

spring:
  application:
    name: order-service
  cloud:
    nacos:
      server-addr: 121.5.101.84:8847
      discovery:
        username: nacos
        password: nacos
        namespace: public